[package]
name = "sloth"
version = "0.1.0"
authors = ["Mitchell Hynes <mitchell.hynes@ecumene.xyz>"]
edition = "2018"

[dependencies]
nalgebra = "0"
crossterm = "0"
tobj = "2"
clap = "2"
stl_io = "0"
